baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

name = "reveal-hugo"
license = "MIT"
licenselink = "https://github.com/dzello/reveal-hugo/blob/master/LICENSE"
homepage = "https://reveal-hugo.dzello.com/"
tags = ["presentation", "revealjs"]
features = ["presentation"]

[author]
name = "Josh Dzielak"
homepage = "https://dzello.com/"

[original]
name = "reveal.js"
homepage = "https://revealjs.com"
repo = "https://github.com/hakimel/reveal.js/"

 [[menu.main]]
  name = "Home"
  url  = "/"
  weight = 0

 [[menu.main]]
  name = "About"
  url  = "about"
  weight = 5

 [[menu.main]]
  name = "Blog"
  url  = "post/"
  weight = 10
